### ISSUE TITLE
Implement `actions/cache` for maven packages

### ISSUE THREAD

**Issue by TheBusyBiscuit** [TheBusyBiscuit/builds#110]
To speed up build times, we should implement the `actions/cache` GitHub action for maven packages here.
An example would look like this:

```yaml
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
```

The key problem here is that we cannot use `**/pom.xml` as this is a JavaScript project first and foremost, we could use another file as a key here.

Workflow file:
https://github.com/TheBusyBiscuit/builds/blob/gh-pages/.github/workflows/build.yml
